-- ============================================================
-- HealthCare Data Management System
-- 03_plsql.sql : Triggers | Functions | Procedures | Cursors
-- UCS310 - Database Management Systems
-- Authors: Saksham Raj (1024030713) | Siddhant Mishra (1024030710)
-- ============================================================

-- ============================================================
-- TRIGGER 1: trg_auto_complete_appointment
-- Auto-marks appointment as Completed when Treatment inserted
-- ============================================================
CREATE OR REPLACE TRIGGER trg_auto_complete_appointment
AFTER INSERT ON TREATMENT
FOR EACH ROW
BEGIN
    UPDATE APPOINTMENT
    SET    Status = 'Completed'
    WHERE  App_ID = :NEW.App_ID
    AND    Status = 'Scheduled';
END;
/

-- ============================================================
-- TRIGGER 2: trg_validate_bill_amount
-- Prevents zero or negative bill amounts
-- ============================================================
CREATE OR REPLACE TRIGGER trg_validate_bill_amount
BEFORE INSERT OR UPDATE ON BILL
FOR EACH ROW
BEGIN
    IF :NEW.Total_Amount <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'Bill amount must be > 0. Received: ' || :NEW.Total_Amount);
    END IF;
END;
/

-- ============================================================
-- FUNCTION 1: fn_patient_total_cost
-- Returns total amount billed for a Patient_ID
-- ============================================================
CREATE OR REPLACE FUNCTION fn_patient_total_cost(p_pid IN VARCHAR2)
RETURN NUMBER IS
    v_total NUMBER := 0;
BEGIN
    SELECT NVL(SUM(b.Total_Amount), 0)
    INTO   v_total
    FROM   BILL b
    JOIN   TREATMENT   t ON b.Treat_ID  = t.Treat_ID
    JOIN   APPOINTMENT a ON t.App_ID    = a.App_ID
    WHERE  a.Patient_ID = p_pid;
    RETURN v_total;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('fn_patient_total_cost error: ' || SQLERRM);
        RETURN -1;
END;
/

-- ============================================================
-- FUNCTION 2: fn_doctor_revenue
-- Returns total revenue generated by a Doctor_ID
-- ============================================================
CREATE OR REPLACE FUNCTION fn_doctor_revenue(p_did IN VARCHAR2)
RETURN NUMBER IS
    v_rev NUMBER := 0;
BEGIN
    SELECT NVL(SUM(b.Total_Amount), 0)
    INTO   v_rev
    FROM   BILL b
    JOIN   TREATMENT   t ON b.Treat_ID  = t.Treat_ID
    JOIN   APPOINTMENT a ON t.App_ID    = a.App_ID
    WHERE  a.Doctor_ID = p_did;
    RETURN v_rev;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
END;
/

-- ============================================================
-- PROCEDURE 1: prc_register_patient
-- Inserts new patient with full exception handling
-- ============================================================
CREATE OR REPLACE PROCEDURE prc_register_patient(
    p_id      IN PATIENT.Patient_ID%TYPE,
    p_name    IN PATIENT.Name%TYPE,
    p_age     IN PATIENT.Age%TYPE,
    p_gender  IN PATIENT.Gender%TYPE,
    p_contact IN PATIENT.Contact%TYPE,
    p_address IN PATIENT.Address%TYPE
) IS
BEGIN
    INSERT INTO PATIENT (Patient_ID, Name, Age, Gender, Contact, Address)
    VALUES (p_id, p_name, p_age, p_gender, p_contact, p_address);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('SUCCESS: Patient registered: ' || p_name || ' [' || p_id || ']');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: Patient ID ' || p_id || ' already exists.');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END;
/

-- ============================================================
-- PROCEDURE 2: prc_book_appointment
-- Books appointment with validation
-- ============================================================
CREATE OR REPLACE PROCEDURE prc_book_appointment(
    p_app_id    IN APPOINTMENT.App_ID%TYPE,
    p_patient   IN APPOINTMENT.Patient_ID%TYPE,
    p_doctor    IN APPOINTMENT.Doctor_ID%TYPE,
    p_date      IN APPOINTMENT.App_Date%TYPE
) IS
    v_pcount NUMBER;
    v_dcount NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_pcount FROM PATIENT WHERE Patient_ID = p_patient;
    SELECT COUNT(*) INTO v_dcount FROM DOCTOR  WHERE Doctor_ID  = p_doctor;

    IF v_pcount = 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 'Patient ' || p_patient || ' not found.');
    END IF;
    IF v_dcount = 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'Doctor ' || p_doctor || ' not found.');
    END IF;

    INSERT INTO APPOINTMENT (App_ID, Patient_ID, Doctor_ID, App_Date, Status)
    VALUES (p_app_id, p_patient, p_doctor, p_date, 'Scheduled');
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Appointment booked: ' || p_app_id);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Booking error: ' || SQLERRM);
END;
/

-- ============================================================
-- PROCEDURE 3: prc_patient_appointments (CURSOR demo)
-- Prints all appointments for a patient
-- ============================================================
CREATE OR REPLACE PROCEDURE prc_patient_appointments(p_pid IN VARCHAR2) IS
    CURSOR c_apt IS
        SELECT a.App_ID, a.App_Date, a.Status,
               d.Name AS Doctor_Name, d.Specialization
        FROM   APPOINTMENT a
        JOIN   DOCTOR d ON a.Doctor_ID = d.Doctor_ID
        WHERE  a.Patient_ID = p_pid
        ORDER  BY a.App_Date DESC;
    v_r   c_apt%ROWTYPE;
    v_cnt NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== Appointments: ' || p_pid || ' ===');
    OPEN c_apt;
    LOOP
        FETCH c_apt INTO v_r;
        EXIT WHEN c_apt%NOTFOUND;
        v_cnt := v_cnt + 1;
        DBMS_OUTPUT.PUT_LINE(
            v_r.App_ID || ' | ' || TO_CHAR(v_r.App_Date,'DD-MON-YYYY') ||
            ' | ' || v_r.Status || ' | Dr. ' || v_r.Doctor_Name ||
            ' (' || v_r.Specialization || ')'
        );
    END LOOP;
    CLOSE c_apt;
    DBMS_OUTPUT.PUT_LINE('Total: ' || v_cnt || ' appointment(s).');
END;
/

-- ============================================================
-- PROCEDURE 4: prc_disease_summary (CURSOR + aggregation)
-- ============================================================
CREATE OR REPLACE PROCEDURE prc_disease_summary IS
    CURSOR c_dis IS
        SELECT t.Disease_Type,
               COUNT(*) AS cases,
               ROUND(AVG(b.Total_Amount),2) AS avg_bill
        FROM   TREATMENT t
        LEFT JOIN BILL b ON b.Treat_ID = t.Treat_ID
        GROUP  BY t.Disease_Type
        ORDER  BY cases DESC;
    v_r c_dis%ROWTYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE(RPAD('Disease',30) || RPAD('Cases',8) || 'Avg Bill (Rs)');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',55,'-'));
    OPEN c_dis;
    LOOP
        FETCH c_dis INTO v_r;
        EXIT WHEN c_dis%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(
            RPAD(NVL(v_r.Disease_Type,'Unknown'),30) ||
            RPAD(v_r.cases,8) || NVL(TO_CHAR(v_r.avg_bill),'N/A')
        );
    END LOOP;
    CLOSE c_dis;
END;
/

BEGIN DBMS_OUTPUT.PUT_LINE('PL/SQL deployed successfully.'); END;
/
